const cities=[
    
    {_Id:0, 
        name:"Barcelona",
        nameImg:"/barcelona.jpg",
       },
       {_Id:1, 
        name:"Belfast",
        nameImg:"/belfast.jpg",
       },
       {_Id:2, 
        name:"Budapest",
        nameImg:"/budapest.jpg",
       },
       {_Id:3, 
        name:"Edimburg",
        nameImg:"/edimburg.jpg",
       },
       {_Id:4, 
        name:"Helsinski",
        nameImg:"/helsinski.jpg",
       },
       {_Id:5, 
        name:"Jakarta",
        nameImg:"/jakarta.jpg",
       },
       {_Id:6, 
        name:"La Plata",
        nameImg:"/laplata.jpg",
       },
       {_Id:7, 
        name:"Lima",
        nameImg:"/lima.jpg",
       },
       {_Id:8, 
        name:"Ljubljana",
        nameImg:"/ljubljana.jpg",
       },
       {_Id:9, 
        name:"Nassau",
        nameImg:"/nassau.jpg",
       },
       {_Id:10, 
        name:"Tokio",
        nameImg:"/tokio.jpg",
       },
       {_Id:11, 
        name:"Viena",
        nameImg:"/viena.jpg",
       },      
                                     
]

export default cities;